import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { LoginFooterNav } from '@/components/LoginFooterNav/LoginFooterNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'X Clone',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <main className="h-full flex-1">{children}</main>
          <LoginFooterNav />
        </div>
      </body>
    </html>
  )
}
